{{- if .Values.storage.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ktm.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ktm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
  {{- with .Values.storage.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
