{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ktm.fullname" . }}-{{ .Release.Namespace }}
  labels:
    {{- include "ktm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ktm.fullname" . }}-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ktm.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
