package delta_test

import (
	"reflect"
	"strings"
	"testing"

	"github.com/Franklin-Osede/kube-time-machine/internal/delta"
)

// FuzzRoundTrip exercises the load-bearing invariant of the package on
// inputs generated by the Go fuzzer:
//
//	Apply(prev, Compute(prev, next)) == next
//
// Run with: go test -fuzz=FuzzRoundTrip -fuzztime=30s ./internal/delta/
// Without -fuzz, only the seed corpus runs as part of `go test ./...`.
func FuzzRoundTrip(f *testing.F) {
	// Seed corpus. Each call exercises one (prev, next) pair the fuzzer
	// will then mutate aggressively.
	f.Add( // typical: modify-and-add-and-remove
		"Deployment/default/api", []byte("v1"),
		"ConfigMap/default/cfg", []byte("c1"),
		"Deployment/default/api", []byte("v2"), // modified
		"Service/default/svc", []byte("s1"), // added; cfg removed
	)
	f.Add( // edge: all empty strings, empty payloads
		"", []byte{}, "", []byte{}, "", []byte{}, "", []byte{},
	)
	f.Add( // edge: identical snapshots (Compute must produce empty delta)
		"A/n/1", []byte("x"), "B/n/2", []byte("y"),
		"A/n/1", []byte("x"), "B/n/2", []byte("y"),
	)

	f.Fuzz(func(t *testing.T,
		kA string, sA []byte,
		kB string, sB []byte,
		kC string, sC []byte,
		kD string, sD []byte,
	) {
		// Two entries per snapshot. If the fuzzer produces colliding keys
		// (e.g. kA == kB) the map naturally collapses to one entry — still
		// a valid Snapshot. The invariant must hold either way.
		prev := delta.Snapshot{
			keyFromString(kA): delta.State(sA),
			keyFromString(kB): delta.State(sB),
		}
		next := delta.Snapshot{
			keyFromString(kC): delta.State(sC),
			keyFromString(kD): delta.State(sD),
		}

		d := delta.Compute(prev, next)
		got := delta.Apply(prev, d)

		if !reflect.DeepEqual(got, next) {
			t.Fatalf("round-trip violated\nprev:  %v\nnext:  %v\ndelta: %+v\ngot:   %v",
				prev, next, d, got)
		}
	})
}

// keyFromString turns a single fuzzer-supplied string into a Key by
// splitting on '/'. Missing components become empty strings. This lets
// the fuzzer drive interesting key-collision patterns from one input.
func keyFromString(s string) delta.Key {
	parts := strings.SplitN(s, "/", 3)
	for len(parts) < 3 {
		parts = append(parts, "")
	}
	return delta.Key{Kind: parts[0], Namespace: parts[1], Name: parts[2]}
}
